export const categories = [
    {
        id:1,
        title:"Education",
        icon:require('../assests/images/education.png'),
        color:"#A95EC2",
    },
    {
        id:2,
        title:"Healthcare",
        icon:require('../assests/images/healthcare.png'),
        color:"#FF768A",
    },
    {
        id:3,
        title:"Shopping",
        icon:require('../assests/images/shopping.png'),
        color:"#EC60AB",
    },
    {
        id:4,
        title:"Food", 
        icon:require('../assests/images/food.png'),
        color:"#FF9E6D",
    },
    {
        id:5,
        title:"Other",
        icon:require('../assests/images/other.png'),
        color:"#FFCB5E",
    }
]
